### ISSUE TITLE
打包之后页面静态化了，但是打包之后的页面没有内容啊

### ISSUE THREAD

**Issue by sht87** [337547038/vite-plugin-seo-prerender#2]
打包之后页面静态化了，但是打包之后的页面没有内容啊

**Comment by sht87** [comment]
版本是0.3.0

**Comment by 337547038** [comment]
可将相关配置及打包控制台信息发上来，以方便定位问题。
同时可clone此示例打包后查看about页面是否正常

**Comment by sht87** [comment]
你这个一个页面没问题，多个页面，打包之后都是同样的内容 ，你可以用你自己的这套代码试下，多个页面静态化时，
vite.config.ts
`export default defineConfig({
  plugins: [
    vue(),
    seoPrerender({
      hashHistory:true,
      routes: ['/about', '/test', '/test1','/test2','/test3'],
      /*publicHtml: true,
      scss: [
        {entry: '/src/assets/test.scss', outDir: '/public/style/test.css'}
      ]*/
    })
  ]
})`
router.ts
`import {createRouter, createWebHashHistory} from 'vue-router'
// @ts-ignore

const routes = [
  {
    path: '/',
    name: '/test',
    component: () => import('./views/test.vue'),
    meta: {
      title: '关于我们1',
      keywords: '关键词3, 关键词4',
      description: '关于我们描述'
    }
  },
  {
    path: '/test1',
    name: '/test1',
    component: () => import('./views/test1.vue'),
    meta: {
      title: '关于我们2',
      keywords: '关键词3, 关键词4',
      description: '关于我们描述'
    }
  },
  {
    path: '/test2',
    name: '/test2',
    component: () => import('./views/test2.vue'),
    meta: {
      title: '关于我们3',
      keywords: '关键词3, 关键词4',
      description: '关于我们描述'
    }
  },
  {
    path: '/test3',
    name: '/test3',
    component: () => import('./views/test3.vue'),
    meta: {
      title: '关于我们4',
      keywords: '关键词3, 关键词4',
      description: '关于我们描述'
    }
  },
  {
    path: '/about',
    name: '/about',
    component: () => import('./views/about/index.vue'),
    meta: {
      title: '关于我们',
      keywords: '关键词3, 关键词4',
      description: '关于我们描述'
    }
  }
]
// console.log(routes)
// 配置路由
const router = createRouter({
 // history: createWebHistory(import.meta.env.BASE_URL),
  history: createWebHashHistory(),
  routes: routes
})

router.afterEach((to) => {
  const {title, keywords, description} = to.meta;
  if (title) {
    document.title = title;
  }
  if (keywords) {
    const metaKeywords = document.querySelector('meta[name="keywords"]');
    if (metaKeywords) {
      metaKeywords.content = keywords;
    }
  }
  if (description) {
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.content = description;
    }
  }
})
export default router
`
其中一个页面的test1页面的内容
`<template>
  <div class="index">
    this is test page1111111
    <div v-for="(item,index) in list" :key="index">
      <p>{{item.name}}</p>
    </div>
    <div>end</div>
  </div>
</template>
<script setup>
  import {ref, onMounted} from 'vue'
  import axios from 'axios'
  
  const list=ref([])
  
  onMounted(() => {
  
  })
</script>
<style>
.index {
  color: antiquewhite;
  font-size: 16px
}
</style>
`

**Comment by 337547038** [comment]
已修复，可使用最新版测试下

**Comment by sht87** [comment]
可以了
