### ISSUE TITLE
network配置不生效和生成的html的内容有误

### ISSUE THREAD

**Issue by yinhaogt** [337547038/vite-plugin-seo-prerender#4]
#### 2.我的页面里有一块内容是数字一直增加的效果，生成的结果里面是还没加完的数字，比如我的效果是一直增加到100，但是渲染的html里面是99，我不清楚这个是不是所有预渲染都有的问题。

请帮忙看一看

**Comment by 337547038** [comment]
1.network为true只是保证在网络请求加载完成后生成渲染页面，为false并不是说不加载网络请求的数据；
2.可以添加一个等待时间的，delay=500(默认500ms)。确保你的页面渲染完成
