### ISSUE TITLE
打包编译错误

### ISSUE THREAD

**Issue by lsq33123** [337547038/vite-plugin-seo-prerender#5]
![Snipaste_2023-10-16_16-02-13](https://github.com/337547038/vite-plugin-seo-prerender/assets/29998078/e9d9831d-b272-4059-8132-b7c490fc2538)
打包编译错误

**Comment by lsq33123** [comment]
![Snipaste_2023-10-16_16-04-47](https://github.com/337547038/vite-plugin-seo-prerender/assets/29998078/be5de7c3-5a81-4fa7-8b89-1baeda855bd7)
我自己的项目打包的时候 好像都没执行你的插件
都没有这句话 [vite-plugin-seo-prerender:routes] is start..

**Comment by 337547038** [comment]
建议删除node_modules使用yarn/pnpm重新安装，所依懒puppeteer包比较大会存在安装不成功等问题

**Comment by lsq33123** [comment]
> 建议删除node_modules使用yarn/pnpm重新安装，所依懒puppeteer包比较大会存在安装不成功等问题

我把render.ts里面的
`  // const browser = await puppeteer.launch(Object.assign({ headless: 'new' }, config.puppeteer || {}));` 
改为
`const browser = await puppeteer.launch(config.puppeteer || {})`
    
就OK了 ，
然后你这个只打包生产环境应该说明一下
