### ISSUE TITLE
生产的预渲染打包文件和实际路由路径无法正确匹配

### ISSUE THREAD

**Issue by Marine-ish** [337547038/vite-plugin-seo-prerender#7]
![Snipaste_2024-02-04_17-02-52](https://github
![Snipaste_2024-02-04_17-03-18](https://github.com/337547038/vite-plugin-seo-prerender/assets/158808615/d50a5fb6-699e-4ead-b7ef-cf2305750197)
.com/337547038/vite-plugin-seo-prerender/assets/158808615/4f15f9ee-bda3-4b9b-923c-1e29631bf27b)
第一张图是配置插件的预渲染的路由,第二张图是我的路由配置
![Snipaste_2024-02-04_17-07-04](https://github.com/337547038/vite-plugin-seo-prerender/assets/158808615/ad0260cd-7e31-40c3-97e2-c45cc7b87e5b)
但是打包出来是路由名称/index.html
但实际在插件配置routes的时候,必须里面的路径要和我的路由path值要一样才能打包出来内容,但是我部署线上后,我实际的路由必须要在现有的path值加上/index.html才能访问的到打包文件里的html内容
就会出现一个冲突,我如果将我自己的路由path加上/index.html,在进行打包就会报错说找不到这个路径,如果我把插件里的routes里的值和我的路由值同步就会出现/路由名称/需要访问index.html,打包后却把我新加的/里面的值作为二级文件并在二级文件里面创建一个html文件
导致我出现要么只能在插件里配置routes, /路由名称 ,我的路由path: /路由名称, 网络请求内容和静态内容都预渲染出来了,但线上后却无法通过我的路由去找到打包后的文件

**Comment by Marine-ish** [comment]
![Snipaste_2024-02-04_17-02-52](https://github.com/337547038/vite-plugin-seo-prerender/assets/158808615/82b2d82b-a3bd-40ea-a75e-8bbb7fd20f8f)

**Comment by 337547038** [comment]
希望访问的路由地址为http://www.xxxx.com/aboutus，但实际需要访问http://www.xxxx.com/aboutus/index.html。这种情况只需要在ngxin里配置默认首页为index.html即可
