### ISSUE TITLE
二级路由无法打包，首页打出来的内容也不对

### ISSUE THREAD

**Issue by superermiao** [337547038/vite-plugin-seo-prerender#8]
![image](https://github.com/337547038/vite-plugin-seo-prerender/assets/24588825/21119d70-f681-4f6e-a170-cb0c6afc743c)
![image](https://github.com/337547038/vite-plugin-seo-prerender/assets/24588825/6bbc3794-be8d-4629-976d-f7b7a02e5cc8)

![image](https://github.com/337547038/vite-plugin-seo-prerender/assets/24588825/048e3fa6-9ee7-4f9a-931a-9b83ea763bcb)

我的/cloud打出来的/cloud.html是ok的，但是/product/pcms打出来的就和首页index.html是一样的，并且，打出来的首页index.html也很奇怪，如下图
![image](https://github.com/337547038/vite-plugin-seo-prerender/assets/24588825/ce978582-0b5d-485a-9ae3-ca69c3beb943)

**Comment by Verdicts-ye** [comment]
改下創建路由 ， webHashHistory 改成 webHistory就行了
